# GCC 5.3.1
Bootstrap: docker
From: centos/devtoolset-4-toolchain-centos7

%environment
    CC=/opt/rh/devtoolset-4/root/bin/gcc
    CXX=/opt/rh/devtoolset-4/root/bin/g++
    LD_LIBRARY_PATH=/opt/rh/devtoolset-4/root/usr/lib/gcc/x86_64-redhat-linux/5.3.1:$LD_LIBRARY_PATH
    unset HOME
    export CC CXX LD_LIBRARY_PATH

%post
  yum -y install epel-release
  yum -y install git
  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
  yum -y install git-lfs

  yum -y install python-pip unzip

  python -m pip install --upgrade pip
  python -m pip install cmake conan

  curl -L -o ninja-linux.zip https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  unzip ninja-linux.zip
  mv ninja /usr/local/bin/ninja
  rm ninja-linux.zip

  yum -y install mesa-libGL-devel
